# H2 - chạy trong bộ nhớ, không cần cài gì
spring.datasource.url=jdbc:h2:mem:studentdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop

# Mở H2 console để xem DB (optional)
spring.h2.console.enabled=true